---
sudo: required

language: python

services:
  - docker

install:
  # molecule version >v2.22 required for compatibility with ansible >2.8
  - pip install molecule==2.22
  #- pip install ansible==2.9.10
  - pip install docker
  # 'jmespath' required by the 'cdh' role (that uses the 'json_query' filter)
  - pip install jmespath
  # install required galaxy roles (postgresql)
  - ansible-galaxy install -r requirements.yml --roles-path roles
  #- ansible-galaxy install geerlingguy.postgresql
script:
  - molecule test
  # TODO test more scenarios (multi-node !?)
  #- molecule test --scenario-name xxx

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
