- name: geerlingguy.postgresql
  # Note: src git+ssh does not just work on travis. Anyway the default from galaxy is fine!
  # scm: git
  # src: git@github.com:geerlingguy/ansible-role-postgresql.git
