---

- name: Add Cloudera Manager yum repository
  yum_repository:
    name: cloudera-manager
    description: Cloudera Manager
    baseurl: "{{ scm_repo_url }}"
    gpgkey: "{{ scm_repo_gpgkey }}"
    gpgcheck: yes
    enabled: yes
  when: 
  - ansible_os_family|lower == "redhat"

#TODO: implement host awareness of task "add postgresql" that is is only run on host with db_server tags
- name: Add PostgreSQL 10 latest yum repository
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
  when:
   # - database_type == "postgresql"
    - inventory_hostname in groups['db_server']    

